apiVersion: v1
kind: Service
metadata:
  name: ping-svc
  namespace: production
spec:
  type: ClusterIP
  selector: 
    app: ping
  ports:
    - port: 3003
      protocol: TCP
      targetPort: 5000
  